version: "3"
services:
  app:
    image: wd-image-processor-app
    build: ../..
    links:
      - wd-server-fx1
      - wd-server-fx2
    environment:
      - WD_BASE_URLS=http://wd-server-fx1:9516 http://wd-server-fx2:9516
      - PROCESSORS_CONFIG_PATH=/app/processors/config.json
    ports:
      - 8080:8080
    volumes:
      - ./processors:/app/processors
  wd-server-fx1:
    image: quay.io/wakaba/firefoxdriver:stable
  wd-server-fx2:
    image: quay.io/wakaba/firefoxdriver:stable
