version: 2
jobs:
  build-app-docker-image:
    docker:
      - image: docker:git
    steps:
      - checkout
      # To enable `docker` command and `docker-compose` command on Docker Executor
      # https://circleci.com/docs/2.0/building-docker-images/
      - setup_remote_docker
          version: 17.11.0-ce
      - run:
          name: Build Docker image
          command: docker build -t app .
workflows:
  version: 2
  build:
    jobs:
      - build-custom-docker-image
